# 100DaysOfCode 

## NumPy 
[Numpy](http://www.numpy.org/) (Numerical Python) - [Docs](https://docs.scipy.org/doc/numpy/user/) [API](https://docs.scipy.org/doc/numpy/reference/index.html) [Tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html)

* fundamental pacakge for scientific computing, provides multi dimentional array object etc.
* numpy array is a table of elements all of the same type
* In NumPy dimensions are called **axes**
* Numpy array have fixed size at creation 
* The elements are all required to be of same data type
* element-by-element operations are the "default mode" when an ndarray is involved and is speedily executed by pre-compiled C code
* **Vectorization** describes the absence of any explicit looping, indexing, etc., in the code - these things are taking place, of course, just “behind the scenes” in optimized, pre-compiled C code.
* **Broadcasting** is the term used to describe the implicit element-by-element behavior of operations

In [1]:
import numpy as np 
a = np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [2]:
# dimensions of the array
a.shape

(5, 2)

In [3]:
#number of dimensions
a.ndim

2

In [4]:
#total number of elements in the array
a.size

10

In [5]:
#the size in bytes of each element of the array
a.itemsize

8

In [6]:
#type of elements in the array
a.dtype.name

'int64'

In [7]:
type(a)

numpy.ndarray

## Array Creation
* can be created from a regular python list or tuple using array function
* the type is deduced from the type of the elements in the sequence
* its a error to call array with multiple numeric arguments
* array transforms sequence of sequence into 2-dimensional arrays and so on
* type of array can also be specified at creation time
* numpy offers several functions to create arrays with initial placeholder content - zeroes()etc
* to create sequence of numbers, numpy provides **arrange**  that returns arrays (range returns list)
* with floating point arguments its not possible to predict the number of elements, better to use function **linspace**

In [8]:
## array creation and type
a = np.array([2,3,4])
print( a.dtype)

b = np.array([2.1, 2,3, 2.4])
print(b.dtype)

int64
float64


In [9]:
## its a error to call array with multiple numeric arguments
d = np.array(1,2,3)

ValueError: only 2 non-keyword arguments accepted

In [10]:
#array transforms sequence of sequence into 2-dimensional arrays 
u = np.array([(1,2,3), (3,4,5)])
u

array([[1, 2, 3],
       [3, 4, 5]])

In [11]:
#type of array can also be specified at creation time
h = np.array([8,9,10], dtype=complex)
h

array([ 8.+0.j,  9.+0.j, 10.+0.j])

In [12]:
#zeroes creates an array of full zeroes
z = np.zeros((3,4), dtype=int)
z

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [13]:
# ones create an array full of ones
o = np.ones((3,3))
print(o)
o.dtype

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


dtype('float64')

In [14]:
# empty creates an array whoes initial content is random 
# and depends on the sate of memory
e = np.empty((2,3))
e

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# to create sequence of numbers, numpy provides **arrange**  
#that returns arrays 

# following command produces numbers between 10 and 30 at step of 5  
np.arange(10,30, 5) 

array([10, 15, 20, 25])

In [16]:
# with floating points argument its not possible to predict the number of elements
np.arange(0,2, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [17]:
# lets use linspace for floating points
np.linspace(0,2, 11)


array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

## Broadcasting
* a and b in an operation could be multidimentional arrays of the same shape or a scalar and an aray, or even two arays of different shapes provided that the smaller array is **expandable** to the shape of the larger in such a way that resulting broadcast in unambiguous. [More on broadcast](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#module-numpy.doc.broadcasting)
* broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of python.
* in broadcasting two dimensions are compatible: a) they are equal or b)one of them is 1
* the size of resulting array is the maximun size along each dimension of the input arrays

In [18]:
## broadcasting example : two array have exactly same shape 
a = np.array([1,2,3])
b = np.array([2,2,2])

a*b


array([2, 4, 6])

In [19]:
#
'''
broadcasting example: array and scalar are combined in an operation
This is similar to above example, in this case b is a scalar and can 
think of it that 'b' is *stretched* into an array with the same shape as 'a' 
'''
#
a = np.array([1,2,3])
b = 2

a*b

array([2, 4, 6])

In [20]:
x = np.arange(4) ## arrange function gives 'n' number of elements  

xx = x.reshape(4,1) #Gives a new shape to an array without changing its data.

y = np.ones(5)

z = np.ones((3,4))


In [21]:
## an operation on  x and y is not possible because it can not be 
# broadcasted based on its shape

print( x.shape)
y.shape

(4,)


(5,)

In [22]:
##since shape of x, y is not same, its an error 
x+y

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [23]:
## now lets try broadcasting on xx and y, in this case y is streched 
xx.shape

(4, 1)

In [24]:
y.shape

(5,)

In [25]:
xx_y = xx + y
print(xx_y)
print(xx_y.shape)

[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]
(4, 5)


In [26]:
y

array([1., 1., 1., 1., 1.])

In [27]:
xx

array([[0],
       [1],
       [2],
       [3]])

In [28]:
## lets try an operation on z and x 
print(z.shape)
x.shape

(3, 4)


(4,)

In [29]:
(z*x).shape

(3, 4)