# 100DaysOfCode Day-11

## Numpy Continued (Part-2)

### Printing 

* If an array is too large, Numpy skips the central part of array and only prints the corner. 


In [1]:
import numpy as np 

In [2]:
# lets create a large array
np.arange(10000).reshape(100,100)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

### Basic Operations
* Arithematic operations on arrays are element-wise
* new array is created and filled with results
* matrix product can be performed using the **@** operator or the **dot** function
* What is **Dot Product**? [Read here](https://www.mathsisfun.com/algebra/matrix-multiplying.html)
* **+=** and ***=** operations modify exsiting array rather than creating a new one
* **Upcasting** 
* many unary operations are methods in ndarray class(computing the sum of all elements in the array)


In [3]:
a = np.array([20,40,60, 80])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [4]:
c = a-b
c

array([20, 39, 58, 77])

In [5]:
b**2

array([0, 1, 4, 9])

In [6]:
10*np.sin(a)

array([ 9.12945251,  7.4511316 , -3.04810621, -9.93888654])

In [7]:
a<50

array([ True,  True, False, False])

In [8]:
# '*' operators elementwise in NumPy arrays 
d = a*b
d

array([  0,  40, 120, 240])

In [9]:
# lets see how * and matrix product is happened
A = np.eye(3)

print(A)
B = np.arange(A.size).reshape(3,3)
B

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
## element-wise product 
A*B

array([[0., 0., 0.],
       [0., 4., 0.],
       [0., 0., 8.]])

In [11]:
# matrix product 
A@B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [12]:
##another way to do matrix product 
A.dot(B)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [13]:
np.dot(A,B)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [14]:
# lets try += and *= operations
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3)) ## this function gives uniform floats between 0 and 1

#lets add 3 in a
a+=3
a

array([[4, 4, 4],
       [4, 4, 4]])

### Upcasting 

In [15]:
#since both a and b have different type of arrays, b is not automatically converted
a *= b


TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [16]:
# in this case a is upcasted to match b's type
b *= a
b

array([[0.83010066, 3.40837571, 3.29361786],
       [3.22046073, 1.04788903, 1.40272161]])

### Unary Operations
* By default, these operations apply as though it were a list of numbers, regardless of its shape
* operation can be specified on a specific axis by specifying **axis** parameter
* What is **Cummulative Sum** ? [Read here](https://www.ablebits.com/office-addins-blog/2016/05/27/excel-cumulative-sum-running-total/)

In [17]:
a = np.random.random((2,3))
a

array([[0.86357711, 0.31328642, 0.96856293],
       [0.63045291, 0.62863632, 0.4764807 ]])

In [18]:
a.sum()

3.880996384166634

In [19]:
a.min()

0.3132864155002786

In [20]:
a.max()

0.9685629256393141

In [21]:
## lets do operation on a specific axis
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
#sum all rows
b.sum(axis=1)

array([ 6, 22, 38])

In [23]:
## cumulative sum along each row
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

### Universal Functions
* mathematical functions such as sin, cos, exp are called "universal function" (ufunc) in NumPy
* these functions operate element-wise
* What is **Exponent**?

In [24]:
X = np.arange(3)
X

array([0, 1, 2])

In [25]:
np.exp(X)

array([1.        , 2.71828183, 7.3890561 ])

### Indexing, Slicing and Iterating
* 1-d arrays can be indexed, sliced and iterated over like lists
* multi-dimensional arrays can have one index per axis
* When fewer indices are provided than the number of axes, the missing indices are considered complete slices **:**
* The dots (...) represent as many colons as needed to produce a complete indexing tuple.For example, if x is an array with 5 axes, then

   * x[1,2,...] is equivalent to x[1,2,:,:,:],
   * x[...,3] to x[:,:,:,:,3] and
   * x[4,...,5,:] to x[4,:,:,5,:].
* Iterating over multidimensional arrays is done with respect to the first axis
*  if one wants to perform an operation on each element in the array, one can use the flat attribute which is an iterator over all the elements of the array

In [26]:
H = np.arange(10)**2

H

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [27]:
## lets index H
H[2]

4

In [28]:
# index from 0 till 3rd element 
H[0:3]

array([0, 1, 4])

In [29]:
#index from 0 till 3rd and return every 2nd element 
H[0:3:2]

array([0, 4])

In [30]:
#slice last 4 elements and set to 100
H[-4:] = 100
H

array([  0,   1,   4,   9,  16,  25, 100, 100, 100, 100])

In [31]:
# reverse 
H[ : : -1]

array([100, 100, 100, 100,  25,  16,   9,   4,   1,   0])

In [32]:
## lets create a multi-dimensional array
T = np.array([[1,2,3], [4,5,6], [7,8,9]])
T

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
# lets index multi-dimensional array
T[2][2]

9

In [34]:
T[0:3, 1]

array([2, 5, 8])

In [35]:
## all produce same result
# for missing index, complete slice (:) is considered
T[-1] #T[2,:] #T[2,]


array([7, 8, 9])

In [36]:
##lets try dots

T[1,...] # equivalent to T[1, :]

array([4, 5, 6])

In [37]:
# lets iterate T 
for row in T:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [38]:
#to perform operation on each elemnt in the array
for ele in T.flat:
    print(ele)

1
2
3
4
5
6
7
8
9
