# 100DaysOfCode Day-12

## NumPy Continued

## Shape Manipulation

* array has a shape given by the number of elements along each axis
* shape of array can be changed by various command but original array is not changed
* **ndarray.resize** method modifies the array itself whereas **reshape** returns its argument with a modified shape

In [1]:
import numpy as np

In [2]:
a = np.floor(10*np.random.random((3,4)))
a

array([[1., 4., 9., 3.],
       [6., 9., 8., 3.],
       [4., 7., 0., 0.]])

In [3]:
a.shape

(3, 4)

In [4]:
#flattens the array
a.ravel()

array([1., 4., 9., 3., 6., 9., 8., 3., 4., 7., 0., 0.])

In [5]:
a.reshape(2,6)

array([[1., 4., 9., 3., 6., 9.],
       [8., 3., 4., 7., 0., 0.]])

In [6]:
a.transpose()  # or a.T

array([[1., 6., 4.],
       [4., 9., 7.],
       [9., 8., 0.],
       [3., 3., 0.]])

In [7]:
# resize do in place changes
a.resize(2,6)
a

array([[1., 4., 9., 3., 6., 9.],
       [8., 3., 4., 7., 0., 0.]])

In [8]:
'''
if a dimension is given as -1 in a reshaping operation,\ 
the other dimension is automatically calculated
'''
a.reshape(3,-1)

array([[1., 4., 9., 3.],
       [6., 9., 8., 3.],
       [4., 7., 0., 0.]])

### Stacking together different arrays


In [9]:
x = np.floor(10*np.random.random((2,2)))
x

array([[8., 6.],
       [9., 9.]])

In [10]:
y = np.floor(10*np.random.random((2,2)))
y

array([[1., 0.],
       [8., 2.]])

In [11]:
# stacking vertically 
np.vstack((x,y))

array([[8., 6.],
       [9., 9.],
       [1., 0.],
       [8., 2.]])

In [12]:
# stacking horizontally
np.hstack((x,y))

array([[8., 6., 1., 0.],
       [9., 9., 8., 2.]])

### Copis and Views
* Python passes mutable objects as references, so function calls make no copy.
* **id()** is a unique identifier of an object 
* The **view** method creates a new array object that looks at the same data.
* Slicing an array returns a view of it
* The copy method makes a complete copy of the array and its data.

In [13]:
a = np.arange(12)
b = a
b is a

True

In [14]:
print( b.shape )
print( a.shape)

(12,)
(12,)


In [15]:
id(a)

4601967280

In [16]:
# lets create view of a
c = a.view()
c is a

False

In [17]:
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [18]:
#changing c's shape does not change the shape of a
c.shape = 2,6

In [19]:
a.shape

(12,)

In [20]:
c[0,0] = 100 # this wil change a's data

In [21]:
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [22]:
a.resize(2,6)
## deep copy 
d = a.copy()
d is a

False

In [23]:
d.base is a

False

In [24]:
d

array([[100,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11]])

In [25]:
a

array([[100,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11]])

In [26]:
d[0,0] = 3

In [27]:
print(d)
print(a)


[[ 3  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[100   1   2   3   4   5]
 [  6   7   8   9  10  11]]
